Author: Walix
site_name: Mille Nuits
theme:
  name: material
nav:
  - SP1: 
    - Mission 1 Maquettage infrastructure reseau: Mission_1_Maquettage_infrastructure_reseau.md
    - Mission 2: Mission 2 sp1.md
    - Mission 3: Mission 3 sp1.md
    - Mission 4 Choix outil tickets: Mission 4 sp1.md
    - Mission 5: Mission 5 sp1.md
  - SP2: 
    - Mission 1 Création d’une documentation avec MkDocs et GitHub Pages: index.md
    - Mission 2: Mission sp2.md
  
